name: Win-xpu-build-UT
on:
    workflow_dispatch:
      inputs:
        win_runner:
            description: Where to run the GHA job?
            type: choice
            options:
            - "icx-4434"
        working_commit:
            description: 'Working commit to pass to xpu.txt'
            required: true
            type: string

env:
    home_dir: '%CD%\torch'
    conda_env: torch_venv
    conda_path: C:\Users\nrvalgo_jenkinsadm\miniforge3
    python_version: '3.10'
    node_proxy: 'http://proxy-us.intel.com:911'
    USE_XPU: 1
    VS2022INSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools'
    ACTIONS_RUNNER_DEBUG: true
    PATH: 'C:\Program Files\Git\cmd;C:\Users\nrvalgo_jenkinsadm\miniforge3;C:\Users\nrvalgo_jenkinsadm\miniforge3\Scripts'

jobs:
  Preparation:
    runs-on: ["${{ inputs.win_runner }}"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        ref: main
        fetch-depth: 0
        path: ${{ env.home_dir }}//actionrepo

    - name: Set conda environment
      shell: cmd
      run: |
        call %conda_path%\Scripts\activate.bat
        call conda remove -n %conda_env% --all -y
        call conda create -n %conda_env% python=3.10 -y
        call conda activate %conda_env%
        call conda remove ucrt -y
        call conda install cmake==3.26.4 --force -y
        call conda list

    - name: Activate Intel Basekit
      shell: cmd
      run: |
        set "basekit_path=C:\Program Files (x86)\Intel\oneAPI"
        call "%basekit_path%\setvars.bat"

  Build-whls:
    runs-on: ["${{ inputs.win_runner }}"]
    needs: [Preparation]
    steps:
    - name: Build Torch
      shell: cmd
      run: |
        call %conda_path%\Scripts\activate.bat %conda_env%

        if exist "%home_dir%\pytorch" (
          rmdir /s /q "%home_dir%\pytorch"
        )

        git clone https://github.com/pytorch/pytorch.git %home_dir%\pytorch
        cd %home_dir%\pytorch
        echo ${{ inputs.working_commit }} > third_party/xpu.txt
        git submodule update --init --recursive
        python -m pip install -r requirements.txt
        python -u setup.py bdist_wheel

    - name: Build TorchVision
      shell: cmd
      run: |
        call %conda_path%\Scripts\activate.bat %conda_env%
        if exist "%home_dir%\vision" rmdir /s /q "%home_dir%\vision"
        git clone https://github.com/pytorch/vision.git %home_dir%\vision
        cd %home_dir%\vision
        git submodule update --init --recursive
        pip install -r docs/requirements.txt

        if exist %home_dir%\pytorch\dist\torch-*.whl (
          pip install %home_dir%\pytorch\dist\torch-*.whl --force-reinstall
        ) else (
          echo "No torch whl found."
          exit
        )

        python setup.py bdist_wheel

        if exist %home_dir%\vision\dist\torchvision-*.whl (
          pip install %home_dir%\vision\dist\torchvision-*.whl --force-reinstall        
        ) else (
          echo "No torchvision whl found."
          exit         
        )

  Unit-tests:
    runs-on: ["${{ inputs.win_runner }}"]
    needs: [Build-whls, Preparation]
    steps:
    - name: Run Unit Tests
      shell: cmd
      run: |
        call %conda_path%\Scripts\activate.bat activate %conda_env%

        if exist "%home_dir%\xpurepo" (
          rmdir /s /q "%home_dir%\xpurepo"
        )

        git clone https://github.com/intel/torch-xpu-ops.git %home_dir%\xpurepo
        cd %home_dir%\xpurepo\examples
        pip install pytest expecttest
        python -m pytest -v | tee "%home_dir%\mtl-bundle-uts.log"
